"""
Clarification Checker.

Reads the claim report (report__*.md) generated by data-claim.py and compares
it against the SQL scripts produced by the excavator to catch contradictions --
e.g., a filter the report says must NOT be applied during extraction appearing
in the SQL, or a cohort constraint implemented incorrectly.
"""

import os

import anthropic

MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-6")

_TOOL = {
    "name": "submit_clarification_check",
    "description": "Submit contradictions found between the claim report and the SQL scripts.",
    "input_schema": {
        "type": "object",
        "properties": {
            "passed": {
                "type": "boolean",
                "description": (
                    "True if no contradictions found between the report's explicit "
                    "constraints and what the SQL scripts actually implement."
                ),
            },
            "violations": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "script": {
                            "type": "string",
                            "description": "Label of the SQL script with the issue (e.g. 'cohort')",
                        },
                        "report_says": {
                            "type": "string",
                            "description": "Exact or paraphrased constraint from the report",
                        },
                        "sql_does": {
                            "type": "string",
                            "description": "What the SQL actually implements that contradicts it",
                        },
                        "remediation": {
                            "type": "string",
                            "description": "Concrete change needed to bring the SQL into compliance",
                        },
                    },
                    "required": ["script", "report_says", "sql_does", "remediation"],
                },
            },
        },
        "required": ["passed", "violations"],
    },
}


def check(
    client: anthropic.Anthropic,
    report_text: str,
    scripts: dict,
) -> dict:
    """
    Compare the claim report's explicit constraints against all SQL scripts.
    Returns dict with keys: passed, violations.
    """
    scripts_block = "\n\n".join(
        f"--- SCRIPT: {label} ---\n{sql}"
        for label, sql in scripts.items()
        if sql
    )

    prompt = f"""You are a consistency auditor for clinical research data extraction.

You are given:
1. A compliance report from an IRB review. The report has multiple sources of authority.
   AUTHORITY ORDER (highest to lowest):
   a. Clarification document -- explicitly labeled "per clarification" or "clarification
      states". These override everything else. If a clarification says X is "downstream
      only" or "not to be applied at extraction", the SQL correctly omits X. Do NOT flag
      the absence of X as a violation.
   b. IRB protocol requirements -- hard rules the SQL must follow.
   c. General report notes -- informational, lower weight.
2. Databricks SQL scripts generated to perform the extraction.

Find contradictions where the SQL violates a higher-authority constraint.

Flag ONLY:
- The SQL applies a filter or restriction the clarification says must NOT be applied
  at extraction time (e.g. SQL filters on BRAF type when clarification says downstream)
- The SQL omits something a clarification explicitly says MUST be included
- The SQL violates an IRB hard requirement (age exclusion, denied data element, etc.)
- The SQL includes an approved data element that the report marks as denied or ambiguous

Do NOT flag:
- Absence of a filter that the clarification deferred to downstream analysis
- Minor wording differences that do not change logic
- Optional features the report notes are not yet needed
- Technical implementation choices not addressed in the report

CLAIM REPORT:
{report_text}

SQL SCRIPTS:
{scripts_block}

Call submit_clarification_check with every contradiction you find.
If the SQL correctly reflects all report constraints, set passed=true and violations=[]."""

    response = client.messages.create(
        model=MODEL,
        max_tokens=2048,
        tools=[_TOOL],
        tool_choice={"type": "tool", "name": "submit_clarification_check"},
        messages=[{"role": "user", "content": prompt}],
    )
    for block in response.content:
        if block.type == "tool_use" and block.name == "submit_clarification_check":
            return block.input

    return {"passed": True, "violations": []}


def print_results(result: dict) -> None:
    status = "OK" if result.get("passed") else "FAIL"
    print(f"\nClarification Check: {status}")
    for v in result.get("violations", []):
        print(f"  [{v['script']}] Report says: {v['report_says']}")
        print(f"           SQL does:    {v['sql_does']}")
        print(f"           Fix:         {v['remediation']}")
    if result.get("passed"):
        print("  All scripts consistent with claim report.")